import { Montserrat } from "next/font/google";
import "./globals.css";
import i18nConfig from "@/i18nConfig";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "All Events",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
